### ISSUE TITLE
How to make new recipes?

### ISSUE THREAD

**Issue by d47081** [scorninpc/php-gtk-cookbook#2]
Contribution is possible here? Not sure that understand how.

Also, documentation wanted for this lib, because I'm reading cpp to understand how does this library work

**Comment by scorninpc** [comment]
hello @d47081 

this repo is just to make clean code to be embed on andor.com.br

**Comment by d47081** [comment]
I don't understand numeration logic, or this repo does not accept NEW examples by PR?

**Comment by scorninpc** [comment]
not accepting new PRs =)

this is a private open, only to my blog

will be nice if you want a example, maybe you can issue and i'll write a post

**Comment by d47081** [comment]
okay, got it.

I have `GtkMessageDialog` draft only, maybe could be useful with minor adaptation:

``` php
// ..
$dialog = new GtkMessageDialog(
    $window->gtk,
    GtkDialogFlags::MODAL,
    GtkMessageType::WARNING,
    GtkButtonsType::OK_CANCEL,
    'Primary text'
);

$dialog->format_secondary_text(
    'Secondary text'
);

if (GtkResponseType::OK == $dialog->run())
{
    // action
}

$dialog->destroy();
```
